version = 0.1

[default.deploy.parameters]
stack_name = "nkust-rollcall"
resolve_s3 = true
s3_prefix = "nkust-rollcall"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FrontendUrl=\"\""
image_repositories = []

[default.global.parameters]
region = "ap-northeast-1"
